/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.DBConnector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Akila
 */
public class MainMenu extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    
    
    public MainMenu() {
        initComponents();
        conn= DBConnector.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genders = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        agebox = new javax.swing.JTextField();
        addressbox = new javax.swing.JTextField();
        pnbox = new javax.swing.JTextField();
        malerbtn = new javax.swing.JRadioButton();
        femalerbtn = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        religonsbox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        subbtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        mediumbox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("mainframe"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 549, -1, 47));

        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 74, -1, -1));

        jLabel3.setText("Age");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 115, -1, -1));

        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 159, -1, -1));

        jLabel5.setText("Phone number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 203, -1, -1));

        jLabel6.setText("Gender");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 242, -1, -1));
        getContentPane().add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 71, 167, -1));
        getContentPane().add(agebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 112, 167, -1));
        getContentPane().add(addressbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 156, 167, -1));
        getContentPane().add(pnbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 200, 167, -1));

        genders.add(malerbtn);
        malerbtn.setText("Male");
        malerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malerbtnActionPerformed(evt);
            }
        });
        getContentPane().add(malerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 238, -1, -1));

        genders.add(femalerbtn);
        femalerbtn.setText("Female");
        femalerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femalerbtnActionPerformed(evt);
            }
        });
        getContentPane().add(femalerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 238, -1, -1));

        jLabel7.setText("Medium");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 305, -1, -1));

        religonsbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buddhism", "Hindu", "Muslim", "Berger" }));
        religonsbox.setToolTipText("");
        getContentPane().add(religonsbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 365, -1, -1));

        jLabel8.setText("Religon");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 368, -1, -1));

        subbtn.setText("Subbmit");
        subbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subbtnActionPerformed(evt);
            }
        });
        getContentPane().add(subbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 441, 77, -1));

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 79, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gettyimages-887303338.jpg"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mediumbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinhla", "Tamil", "English", " " }));
        getContentPane().add(mediumbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 299, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setBackground(new java.awt.Color(51, 255, 51));
        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel2.setText(" Registration");
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 0, -1, -1));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subbtnActionPerformed
        String name;
        int age;
        String address;
        int pn;
        String gender;
        String lan;
        String religon;
        
        name=namebox.getText();
        age=Integer.parseInt(agebox.getText());
        address=addressbox.getText();
        pn=Integer.parseInt(pnbox.getText());
              
        religon=religonsbox.getSelectedItem().toString();
        
        if(malerbtn.isSelected()){
            gender="male";
        }
        else{
            
            gender="female";
            
        }
        
        lan=mediumbox.getSelectedItem().toString();
        
          int up=JOptionPane.showConfirmDialog(null,"Do you want to Submit");
        try{
        
        String sql="INSERT INTO register(name,age,address,phone,gender,lan,religon)VALUE ('"+name+"','"+age+"','"+address+"','"+pn+"','"+gender+"','"+lan+"','"+religon+"')";
        pst=conn.prepareStatement(sql);
        pst.execute();
        JOptionPane.showMessageDialog(null, "Subbmit Success");
        setVisible(false);
        new MainMenu().setVisible(true);
        }
        
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        setVisible(false);
        new MainMenu().setVisible(true);
        
        }
    }//GEN-LAST:event_subbtnActionPerformed

    private void malerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malerbtnActionPerformed
   
    }//GEN-LAST:event_malerbtnActionPerformed

    private void femalerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femalerbtnActionPerformed
     
    }//GEN-LAST:event_femalerbtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
             this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Main q1= new Main();  
            q1.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressbox;
    private javax.swing.JTextField agebox;
    private javax.swing.JRadioButton femalerbtn;
    private javax.swing.ButtonGroup genders;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton malerbtn;
    private javax.swing.JComboBox<String> mediumbox;
    private javax.swing.JTextField namebox;
    private javax.swing.JTextField pnbox;
    private javax.swing.JComboBox<String> religonsbox;
    private javax.swing.JButton subbtn;
    // End of variables declaration//GEN-END:variables
}
